openapi: 3.0.0
info:
  title: AAS
  version: 1.0.0
servers:
  - url: https://130.162.195.228
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
paths:
  /mhs714220032/products:
    get:
      tags:
        - default
      summary: GetProduct
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /mhs714220032/login:
    post:
      tags:
        - default
      summary: UserLogin
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                username: rania
                password: thv301295
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /mhs714220032/regis:
    post:
      tags:
        - default
      summary: UserRegistration
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                username: thv
                password: thv301295
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /mhs714220032/products:
    post:
      tags:
        - default
      summary: PostProduct
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: celana
                description: baru
                price: 400000
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /mhs714220032/orders:
    post:
      tags:
        - default
      summary: PostOrder
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                user_id: 2
                product_id: 2
                order_status: success
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - default
      summary: GetOrder
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /mhs714220032/products/3:
    put:
      tags:
        - default
      summary: PutProduct
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: rok
                description: baru
                price: 400000
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /mhs714220032/orders/2:
    put:
      tags:
        - default
      summary: PutOrders
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                user_id: 2
                product_id: 2
                order_status: success
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - default
      summary: DeleteOrder
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /mhs714220032/products/6:
    delete:
      tags:
        - default
      summary: DeleteProduct
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
